export { HeroSection } from './HeroSection'
export { WhyChooseUs } from './WhyChooseUs'
export { PhilosophySection } from './PhilosophySection'
export { CanadianCurriculum } from './CanadianCurriculum'
export { SchoolGallery } from './SchoolGallery'
export { EventSection } from './EventSection'
export { MBAroundTheWorld } from './MBAroundTheWorld'
export { LeadCaptureForm } from './LeadCaptureForm'

// Additional sections available
export { TrustBar } from './TrustBar'
export { ProgramCards } from './ProgramCards'
export { StatsCounter } from './StatsCounter'
export { DailySchedule } from './DailySchedule'
export { TeacherTeam } from './TeacherTeam'
export { Testimonials } from './Testimonials'
export { NewsGrid } from './NewsGrid'
export { PartnersSection } from './PartnersSection'
export { VideoSection } from './VideoSection'
