export const SCHOOL_INFO = {
  NAME: 'Sunshine Maple Bear International Kindergarten',
  NAME_EN: 'Sunshine Maple Bear International Kindergarten',
  TAGLINE: 'Premium Canadian International Early Childhood Education — 100% English',
  TAGLINE_EN: 'Premium Canadian International Early Childhood Education — 100% English',
  ADDRESS_PALACE: 'Sunshine Palace Building, 13 Linh Nam, Vinh Tuy Ward, Hanoi',
  ADDRESS_RIVERSIDE: 'Sunshine Riverside Urban Area, Phu Thuong Ward, Tay Ho, Hanoi',
  ADDRESS_GARDEN: 'Sunshine Garden Building, Duong Van Be Street, Vinh Tuy Ward, Hanoi',
  ADDRESS: 'Sunshine City, Ciputra Urban Area, Nam Thang Long, Hanoi',
  PHONE: '094 254 6655',
  PHONE_TH: '090 154 6655',
  PHONE_THCS: '091 754 6655',
  EMAIL: 'admissions@sunshinemaplebear.edu.vn',
  WORKING_HOURS: '08:00 - 17:00',
  WEBSITE: 'https://sunshinemaplebear.edu.vn',
  MAP_URL: 'https://maps.google.com/?q=Sunshine+Maple+Bear+Hanoi',
  YOUTUBE_INTRO: 'https://www.youtube.com/embed/2PWdT772-IY',
  YOUTUBE_LINK: 'https://youtu.be/2PWdT772-IY',
  CORE_VALUES: ['Self-reliance', 'Respect', 'Empathy', 'Ambition', 'Shine'],
  CORE_VALUES_EN: ['Self-reliance', 'Respect', 'Empathy', 'Ambition', 'Shine'],
  GLOBAL_STATS: {
    schools: 547,
    countries: 39,
    campuses: 5,
  },
}

export const CAMPUSES = [
  {
    id: 'palace',
    name: 'Palace Campus',
    nameEn: 'Palace Campus',
    address: 'Sunshine Palace Building, 13 Linh Nam, Vinh Tuy Ward, Hanoi',
    phone: '094 254 6655, press 1',
    level: 'Kindergarten',
  },
  {
    id: 'riverside',
    name: 'Riverside Campus',
    nameEn: 'Riverside Campus',
    address: 'Sunshine Riverside Urban Area, Phu Thuong Ward, Tay Ho, Hanoi',
    phone: '094 254 6655, press 2',
    level: 'Kindergarten + Primary + Secondary',
  },
  {
    id: 'garden',
    name: 'Garden Campus',
    nameEn: 'Garden Campus',
    address: 'Sunshine Garden Building, Duong Van Be Street, Vinh Tuy Ward, Hanoi',
    phone: '094 254 6655, press 3',
    level: 'Kindergarten',
  },
]

export const SCHOOL_IMAGES = {
  render: {
    hanhLang1: '/images/render/HANH_LANG_1_.jpg',
    hanhLang2: '/images/render/HANH_LANG_2_.jpg',
    lopHoc1: '/images/render/LOP_HOC_DIEN_HINH_1_.jpg',
    lopHoc2: '/images/render/LOP_HOC_DIEN_HINH_2_.jpg',
    lopHoc3: '/images/render/LOP_HOC_DIEN_HINH_3_.jpg',
    lopHoc4: '/images/render/LOP_HOC_DIEN_HINH_4_.jpg',
    lopHoc5: '/images/render/LOP_HOC_DIEN_HINH_5_.jpg',
    phongChucNang1: '/images/render/PHONG_CHUC_NANG_1_.jpg',
    phongChucNang2: '/images/render/PHONG_CHUC_NANG_2_.jpg',
    phongChucNang3: '/images/render/PHONG_CHUC_NANG_3_.jpg',
    phongChucNang4: '/images/render/PHONG_CHUC_NANG_4_.jpg',
    phongYTe1: '/images/render/PHONG_Y_TE_1_.jpg',
    phongYTe2: '/images/render/PHONG_Y_TE_2_.jpg',
    phongYTe3: '/images/render/PHONG_Y_TE_3_.jpg',
    thuVien1: '/images/render/THU_VIEN_1_.jpg',
    thuVien2: '/images/render/THU_VIEN_2_.jpg',
    thuVien3: '/images/render/THU_VIEN_3_.jpg',
    thuVien4: '/images/render/THU_VIEN_4_.jpg',
    thuVien5: '/images/render/THU_VIEN_5_.jpg',
    thuVien6: '/images/render/THU_VIEN_6_.jpg',
    thuVien7: '/images/render/THU_VIEN_7_.jpg',
    thuVien8: '/images/render/THU_VIEN_8_.jpg',
    vanPhong: '/images/render/VAN_PHONG.jpg',
  },
  logo: '/logo.png',
}

// Bear-themed class names matching SMB official naming
export const BEAR_CLASSES = [
  {
    id: 'teddy',
    name: 'Teddy Bears Class',
    nameEn: 'Teddy Bears Class',
    emoji: '🧸',
    age: '12 – 24 months',
    ageEn: '12 – 24 months',
    level: 'Toddler',
    desc: 'A comprehensive care and development program for toddlers in their first stage of discovery. Teacher-to-student ratio of 1:4, ensuring the most dedicated care.',
    descEn: 'A comprehensive care and development program for toddlers in their first stage of discovery. Teacher-to-student ratio of 1:4, ensuring the most dedicated care.',
    image: SCHOOL_IMAGES.render.lopHoc1,
    color: '#EAB308',
  },
  {
    id: 'koala',
    name: 'Koala Bears Class',
    nameEn: 'Koala Bears Class',
    emoji: '🐨',
    age: '2 – 3 years',
    ageEn: '2 – 3 years',
    level: 'Nursery',
    desc: 'A stage of remarkable language development. Teacher-to-student ratio of 1:6, maximum 18 students per class, building confident communicators.',
    descEn: 'A stage of remarkable language development. Teacher-to-student ratio of 1:6, maximum 18 students per class, building confident communicators.',
    image: SCHOOL_IMAGES.render.lopHoc2,
    color: '#3B82F6',
  },
  {
    id: 'panda',
    name: 'Panda Bears Class',
    nameEn: 'Panda Bears Class',
    emoji: '🐼',
    age: '3 – 4 years',
    ageEn: '3 – 4 years',
    level: 'Junior Kindergarten',
    desc: 'Children develop logical thinking and teamwork skills through inquiry-based learning. Teacher-to-student ratio of 1:7, maximum 20 students per class.',
    descEn: 'Children develop logical thinking and teamwork skills through inquiry-based learning. Teacher-to-student ratio of 1:7, maximum 20 students per class.',
    image: SCHOOL_IMAGES.render.lopHoc5,
    color: '#22C55E',
  },
  {
    id: 'sun',
    name: 'Sun Bears Class',
    nameEn: 'Sun Bears Class',
    emoji: '☀️',
    age: '4 – 5 years',
    ageEn: '4 – 5 years',
    level: 'Senior Kindergarten 1',
    desc: 'Stimulating creativity and a love of learning through project-based exploration. Teacher-to-student ratio of 1:8, maximum 21 students per class.',
    descEn: 'Stimulating creativity and a love of learning through project-based exploration. Teacher-to-student ratio of 1:8, maximum 21 students per class.',
    image: SCHOOL_IMAGES.render.thuVien2,
    color: '#F97316',
  },
  {
    id: 'polar',
    name: 'Polar Bears Class',
    nameEn: 'Polar Bears Class',
    emoji: '🐻‍❄️',
    age: '5 – 6 years',
    ageEn: '5 – 6 years',
    level: 'Senior Kindergarten 2',
    desc: 'Building a solid foundation for Grade 1 readiness with enhanced literacy and numeracy skills. Teacher-to-student ratio of 1:10, maximum 22 students per class.',
    descEn: 'Building a solid foundation for Grade 1 readiness with enhanced literacy and numeracy skills. Teacher-to-student ratio of 1:10, maximum 22 students per class.',
    image: SCHOOL_IMAGES.render.lopHoc4,
    color: '#C8102E',
  },
]

export const GRADE_LEVELS = {
  TEDDY: { id: 'teddy', label: 'Teddy Bears', age: '12 - 24 months' },
  KOALA: { id: 'koala', label: 'Koala Bears', age: '2 - 3 years' },
  PANDA: { id: 'panda', label: 'Panda Bears', age: '3 - 4 years' },
  SUN: { id: 'sun', label: 'Sun Bears', age: '4 - 5 years' },
  POLAR: { id: 'polar', label: 'Polar Bears', age: '5 - 6 years' },
}

export const MOCK_BLOG_POSTS = [
  {
    id: '1',
    title: 'Sunshine Talk English Speech Contest 2026 Launched',
    titleEn: 'Sunshine Talk English Speech Contest 2026 Launched',
    excerpt: 'Enhancing academic excellence and building confident English communication skills through our annual speech competition.',
    excerptEn: 'Enhancing academic excellence and building confident English communication skills through our annual speech competition.',
    date: '2026-04-23',
    category: 'Events',
    categoryEn: 'Events',
    image: SCHOOL_IMAGES.render.lopHoc1,
  },
  {
    id: '2',
    title: 'Spelling Bee 2025 — School-Wide English Spelling Contest',
    titleEn: 'Spelling Bee 2025 — School-Wide English Spelling Contest',
    excerpt: 'One of our key educational objectives at Maple Bear is comprehensive language skills development for every learner.',
    excerptEn: 'One of our key educational objectives at Maple Bear is comprehensive language skills development for every learner.',
    date: '2025-11-17',
    category: 'News',
    categoryEn: 'News',
    image: SCHOOL_IMAGES.render.lopHoc2,
  },
  {
    id: '3',
    title: 'Grand Opening Celebration — A New Era at SMB Schools',
    titleEn: 'Grand Opening Celebration — A New Era at SMB Schools',
    excerpt: 'Sharing in the excitement with students nationwide, the opening ceremony at SMB was truly a memorable milestone.',
    excerptEn: 'Sharing in the excitement with students nationwide, the opening ceremony at SMB was truly a memorable milestone.',
    date: '2025-09-06',
    category: 'Events',
    categoryEn: 'Events',
    image: SCHOOL_IMAGES.render.hanhLang1,
  },
]

export const MOCK_EVENTS = [
  {
    id: '1',
    title: 'Culture Day 2026 — Celebrating Diversity Through Joy',
    date: '2026-05-20',
    time: '08:30 - 11:30',
    location: 'Sunshine Maple Bear Schoolyard',
    image: SCHOOL_IMAGES.render.thuVien1,
    description: 'A vibrant multicultural festival featuring international food booths, traditional games, and student art performances.',
  },
  {
    id: '2',
    title: 'Sunshine Olympics — Sports Day 2026',
    date: '2026-06-15',
    time: '14:00 - 16:30',
    location: 'Level 2 Auditorium',
    image: SCHOOL_IMAGES.render.phongChucNang1,
    description: 'Our annual sports day where young athletes compete in collaborative events, building physical fitness and team spirit.',
  },
  {
    id: '3',
    title: 'Workshop: Parenting in the Digital Age',
    date: '2026-07-10',
    time: '09:00 - 11:00',
    location: 'Multi-Purpose Hall — Sunshine City',
    image: SCHOOL_IMAGES.render.lopHoc3,
    description: 'Expert insights from leading educators on guiding and protecting children in today\'s digital landscape.',
  },
]
